import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'dashboard/dashboard-overview',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/accessing-petaladdin',
        'getting-started/clinic-setup',
        'getting-started/user-roles-overview',
        'getting-started/login-screen',
        'getting-started/forgot-password-screen',
        'getting-started/reset-password-screen',
      ],
    },
    {
      type: 'category',
      label: 'Front Desk',
      items: [
        'pet-parents/managing-pet-parents',
        'pet-parents/create-pet-parent-screen',
        'pet-parents/edit-pet-parent-screen',
        'pets/managing-pets',
        'pets/create-pet-screen',
        'pets/edit-pet-screen',
        'appointments/managing-appointments',
        'appointments/check-in-check-out',
        'appointments/appointments-list-screen',
        'appointments/create-appointment-screen',
        'appointments/edit-appointment-screen',
        'appointments/appointment-details-screen',
        'appointments/appointment-setup-screen',
        'workflows/front-desk-workflow',
      ],
    },
    {
      type: 'category',
      label: 'Clinical Workflow',
      items: [
        'patient-records/patient-profiles',
        'patient-records/pet-profile-workspace',
        'clinical/consultations-treatment-notes',
        'clinical/consultations-list-screen',
        'clinical/create-consultation-screen',
        'clinical/edit-consultation-screen',
        'clinical/consultation-details-screen',
        'clinical/prescription-templates-screen',
        'clinical/doctor-profiles',
        'clinical/vaccination-schedule-management',
        'clinical/deworming-schedule-management',
        'clinical/certificate-workspace',
      ],
    },
    {
      type: 'category',
      label: 'Billing and Inventory',
      items: [
        'billing/pos-checkout-workflow',
        'billing/invoices-payments',
        'billing/invoice-management',
        'billing/refund-workflow',
        'billing/invoice-refund-record',
        'billing/quotation-management',
        'billing/coupon-management',
        'billing/membership-plan-management',
        'inventory/managing-medicines-stock',
        'inventory/supplier-management',
        'inventory/product-category-management',
        'inventory/product-catalog-management',
        'inventory/create-product-screen',
        'inventory/edit-product-screen',
        'inventory/product-details-screen',
        'inventory/purchase-management',
        'inventory/create-purchase-screen',
        'inventory/edit-purchase-screen',
        'inventory/purchase-details-screen',
        'inventory/stock-adjustment-management',
        'inventory/create-stock-adjustment-screen',
        'inventory/stock-adjustment-details-screen',
        'inventory/product-import-workflow',
        'inventory/stock-adjustment-import-screen',
        'inventory/stock-adjustment-import-workflow',
        'billing/create-invoice-screen',
        'billing/edit-invoice-screen',
        'billing/invoice-print-screen',
      ],
    },
    {
      type: 'category',
      label: 'Administration',
      items: [
        'admin/users-roles',
        'admin/my-account',
        'admin/clinic-switcher',
        'admin/staff-user-management',
        'admin/permission-roles',
        'admin/access-audit',
        'admin/clinic-management',
        'admin/clinic-settings',
        'admin/communication-logs',
        'admin/subscription-management',
        'reports/reports-overview',
        'reports/daily-financial-reports',
        'reports/finance-report',
        'reports/promotions-report',
        'reports/doctor-performance-report',
        'reports/appointments-report',
        'reports/clinical-report',
        'reports/inventory-report',
      ],
    },
    {
      type: 'category',
      label: 'Help',
      items: [
        'troubleshooting/common-issues',
        'troubleshooting/passwords-browser-support',
      ],
    },
  ],
};

export default sidebars;
